# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 391)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stacked_widget_pilha_pags = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stacked_widget_pilha_pags.setGeometry(QtCore.QRect(0, 10, 421, 331))
        self.stacked_widget_pilha_pags.setObjectName("stacked_widget_pilha_pags")
        self.page_cadastro_contato = QtWidgets.QWidget()
        self.page_cadastro_contato.setObjectName("page_cadastro_contato")
        self.label_5 = QtWidgets.QLabel(parent=self.page_cadastro_contato)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 101, 71))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(parent=self.page_cadastro_contato)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 371, 31))
        self.label_4.setObjectName("label_4")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.page_cadastro_contato)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 110, 371, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.line_edit_nome_contato = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.line_edit_nome_contato.setObjectName("line_edit_nome_contato")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_edit_nome_contato)
        self.line_edit_telefone_contato = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.line_edit_telefone_contato.setObjectName("line_edit_telefone_contato")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_edit_telefone_contato)
        self.label_3 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.line_edit_emailcontato = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.line_edit_emailcontato.setObjectName("line_edit_emailcontato")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_edit_emailcontato)
        self.push_button_salvar_contato = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.push_button_salvar_contato.setStyleSheet("background-color: rgb(116, 255, 132);")
        self.push_button_salvar_contato.setObjectName("push_button_salvar_contato")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.push_button_salvar_contato)
        self.label_msg_sucesso = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_msg_sucesso.setObjectName("label_msg_sucesso")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_msg_sucesso)
        self.label_msg_erro = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_msg_erro.setObjectName("label_msg_erro")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_msg_erro)
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.label_5.raise_()
        self.formLayoutWidget.raise_()
        self.label_4.raise_()
        self.stacked_widget_pilha_pags.addWidget(self.page_cadastro_contato)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_6 = QtWidgets.QLabel(parent=self.page_2)
        self.label_6.setGeometry(QtCore.QRect(100, 80, 251, 16))
        self.label_6.setObjectName("label_6")
        self.stacked_widget_pilha_pags.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stacked_widget_pilha_pags.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Cadastro de Contatos:</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Nome:"))
        self.line_edit_nome_contato.setPlaceholderText(_translate("MainWindow", "Digite o nome do contato"))
        self.line_edit_telefone_contato.setPlaceholderText(_translate("MainWindow", "Digite o telefone do contato"))
        self.label_3.setText(_translate("MainWindow", "Email:"))
        self.line_edit_emailcontato.setPlaceholderText(_translate("MainWindow", "Digite o email do contato"))
        self.push_button_salvar_contato.setToolTip(_translate("MainWindow", "Clique para salvar um contato"))
        self.push_button_salvar_contato.setText(_translate("MainWindow", "Salvar Contato"))
        self.label_msg_sucesso.setText(_translate("MainWindow", "Sucesso"))
        self.label_msg_erro.setText(_translate("MainWindow", "Erro"))
        self.label_2.setText(_translate("MainWindow", "Telefone:"))
        self.label_6.setText(_translate("MainWindow", "Ola"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
